# Generated by Django 2.2.27 on 2024-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('mpaaRating', models.CharField(max_length=100)),
                ('userRating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
